/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Design = IDL.Record({
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'data' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
});

export const idlService = IDL.Service({
  'deleteDesign' : IDL.Func([IDL.Nat], [], []),
  'getDesign' : IDL.Func([IDL.Nat], [Design], ['query']),
  'listDesigns' : IDL.Func([], [IDL.Vec(Design)], ['query']),
  'saveDesign' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Design = IDL.Record({
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'data' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
  });
  
  return IDL.Service({
    'deleteDesign' : IDL.Func([IDL.Nat], [], []),
    'getDesign' : IDL.Func([IDL.Nat], [Design], ['query']),
    'listDesigns' : IDL.Func([], [IDL.Vec(Design)], ['query']),
    'saveDesign' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };